feat: group samples by genotype and medium definitions
DD-DeCaF/iloop-to-model pull request #11
Opened 2017-06-28 12:44 UTC by sgalkina

2017-06-28 16:15 UTC, hredestig requested changes

2017-06-28 16:15 UTC, hredestig commented on iloop_to_model/app.py
> +        sample.strain.pool.id,
we don't  need to also include `sample.strain.id` here?

2017-06-28 20:14 UTC, sgalkina commented on iloop_to_model/app.py
> +        sample.strain.pool.id,
that's a valid concern, but in this case no - the thing about fermentation experiment according to Emre that the distinction is actually in the pool, and all the strains in one pool have different identifiers but the same genotype. So using strain ids would only lead to not grouping samples at all

2017-06-29 07:08 UTC, hredestig commented on iloop_to_model/app.py
> +        sample.strain.pool.id,
okay

2017-06-29 07:08 UTC, hredestig approved these changes

2017-06-29 07:10 UTC, merged